### PR TITLE
docs: fix/update readme

### PR DESCRIPTION
**Pull request by jsejcksn**
Uses updated example module proposed in  https://github.com/lucacasonato/esbuild_deno_loader/commit/37ac2f8c69c1bd10e4c919494b11762867334d2e

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks!

**Comment by jsejcksn** [comment]
@lucacasonato It looks like [one of the workflows is stuck on "Run tests"](https://github.com/lucacasonato/esbuild_deno_loader/actions/runs/4424278698/jobs/8105609770?pr=48) for more than a couple of hours. Can it be restarted?

**Comment by jsejcksn** [comment]
> @lucacasonato It looks like [one of the workflows is stuck on "Run tests"](https://github.com/lucacasonato/esbuild_deno_loader/actions/runs/4424278698/jobs/8105609770?pr=48) for more than a couple of hours. Can it be restarted?

@lucacasonato Maybe closing and reopening will re-run the checks? 🤷

**Comment by jsejcksn** [comment]
@lucacasonato It looks like there are some problems in the CI workflows that are not related to this PR. Let me know if there's anything needed from me.

**Comment by roj1512** [comment]
I think this should be merged or something.

**Pull request merged**
